version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'avaliacao-api'
    ports:
      - "8085:8085"
    depends_on:
      avaliacaodb:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL= jdbc:postgresql://avaliacaodb:5432/user
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  avaliacaodb:
    image: postgres:13.1
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "user" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - APP_DB_USER=usuario
      - APP_DB_PASS=senha
      - APP_DB_NAME=avaliacao
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8383:8080"

