spring:
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
        use_jdbc_metadata_defaults: false
    database-platform : org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://${DATABASE_URL}/${DATABASE_NAME}
    driverClassName : org.postgresql.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 1

    maxActive: 1
  server:
    port: 8085

    DATABASE_URL= jdbc:postgresql://avaliacaodb:5432/user
    DATABASE_NAME
    - DATABASE_USERNAME=user
    - DATABASE_PASSWORD=pass

